# -*- coding: utf-8 -*-
"""modle1-ot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Co_D91QPYmWl8bExSxxnpmghj2NjqEB3
"""

import pandas as pd
import numpy as np
from statsmodels.formula.api import ols
from sklearn.metrics import mean_squared_error
import pickle

df = pd.read_csv("cardekho_dataset.csv")

print("Dataset Shape:", df.shape)
df.head()

def remove_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return df[(df[column] >= lower) & (df[column] <= upper)]

columns = ['selling_price', 'km_driven', 'mileage', 'engine', 'max_power']

df_clean = df.copy()

for col in columns:
    df_clean = remove_outliers(df_clean, col)

print("Before Cleaning:", df.shape)
print("After Cleaning:", df_clean.shape)

model = ols(
    'selling_price ~ vehicle_age + km_driven + brand + seller_type + fuel_type + transmission_type + mileage + engine + max_power + seats',
    data=df_clean
).fit()

print(model.summary())

predictions = model.predict(df_clean)

r2 = model.rsquared
rmse = np.sqrt(mean_squared_error(df_clean['selling_price'], predictions))

print("R²:", r2)
print("RMSE:", rmse)

pickle.dump(model, open("model.pkl", "wb"))
print("Model saved successfully!")

import streamlit as st
import pandas as pd
import pickle

# Load model
model = pickle.load(open("model.pkl", "rb"))

st.set_page_config(page_title="Car Price Predictor", layout="wide")

st.title("🚗 Car Price Prediction")

st.sidebar.header("Enter Car Details")

# Inputs
vehicle_age = st.sidebar.slider("Vehicle Age", 0, 20, 5)
km_driven = st.sidebar.number_input("KM Driven", 0, 300000, 50000)

brand = st.sidebar.selectbox("Brand", ["Maruti", "Hyundai", "Honda", "Toyota", "Mahindra"])

seller_type = st.sidebar.selectbox("Seller Type", ["Individual", "Dealer"])
fuel_type = st.sidebar.selectbox("Fuel Type", ["Petrol", "Diesel", "CNG"])

transmission_type = st.sidebar.selectbox("Transmission", ["Manual", "Automatic"])

mileage = st.sidebar.number_input("Mileage", 0.0, 40.0, 18.0)
engine = st.sidebar.number_input("Engine (CC)", 500, 5000, 1200)
max_power = st.sidebar.number_input("Max Power", 20.0, 300.0, 80.0)
seats = st.sidebar.slider("Seats", 2, 10, 5)

# Input DataFrame
input_data = pd.DataFrame({
    'vehicle_age': [vehicle_age],
    'km_driven': [km_driven],
    'brand': [brand],
    'seller_type': [seller_type],
    'fuel_type': [fuel_type],
    'transmission_type': [transmission_type],
    'mileage': [mileage],
    'engine': [engine],
    'max_power': [max_power],
    'seats': [seats]
})

# Prediction
if st.button("Predict Price"):
    try:
        pred = model.predict(input_data)[0]
        st.success(f"Estimated Price: ₹{pred:,.2f}")
    except Exception as e:
        st.error(f"Error: {e}")

print(df['brand'].unique())

